FROM node:21-alpine3.18
WORKDIR /app
# Install Angular CLI globally within the container
#RUN npm install -g @angular/cli
COPY package*.json .
RUN npm install
COPY . .
#EXPOSE "4200"
#CMD [ "npm", "start" ]
CMD [ "ng", "serve" , "--host", "0.0.0.0", "--disable-host-check"]
#RUN npm run build